// Entidades federativas de México con su clave corta, para el perfil (D-068)
export const MEXICAN_STATES = [
  ['AGS', 'Aguascalientes'],
  ['BC', 'Baja California'],
  ['BCS', 'Baja California Sur'],
  ['CAMP', 'Campeche'],
  ['CHIS', 'Chiapas'],
  ['CHIH', 'Chihuahua'],
  ['CDMX', 'Ciudad de México'],
  ['COAH', 'Coahuila'],
  ['COL', 'Colima'],
  ['DGO', 'Durango'],
  ['MEX', 'Estado de México'],
  ['GTO', 'Guanajuato'],
  ['GRO', 'Guerrero'],
  ['HGO', 'Hidalgo'],
  ['JAL', 'Jalisco'],
  ['MICH', 'Michoacán'],
  ['MOR', 'Morelos'],
  ['NAY', 'Nayarit'],
  ['NL', 'Nuevo León'],
  ['OAX', 'Oaxaca'],
  ['PUE', 'Puebla'],
  ['QRO', 'Querétaro'],
  ['QROO', 'Quintana Roo'],
  ['SLP', 'San Luis Potosí'],
  ['SIN', 'Sinaloa'],
  ['SON', 'Sonora'],
  ['TAB', 'Tabasco'],
  ['TAMS', 'Tamaulipas'],
  ['TLAX', 'Tlaxcala'],
  ['VER', 'Veracruz'],
  ['YUC', 'Yucatán'],
  ['ZAC', 'Zacatecas'],
  ['EXT', 'Vivo fuera de México'],
] as const satisfies readonly (readonly [string, string])[];
