// Especialidades de entrada directa del ENARM para elegir la especialidad objetivo (D-068).
// Lista tomada de fuentes públicas sobre el 50º ENARM 2026. Está por verificar contra la
// convocatoria oficial de la CIFRHS, que no se pudo abrir desde el entorno de desarrollo
export const SPECIALTIES = [
  ['anatomic_pathology', 'Anatomía Patológica'],
  ['anesthesiology', 'Anestesiología'],
  ['audiology', 'Audiología, Otoneurología y Foniatría'],
  ['clinical_quality', 'Calidad de la Atención Clínica'],
  ['general_surgery', 'Cirugía General'],
  ['epidemiology', 'Epidemiología'],
  ['medical_genetics', 'Genética Médica'],
  ['geriatrics', 'Geriatría'],
  ['obstetrics_gynecology', 'Ginecología y Obstetricia'],
  ['diagnostic_imaging', 'Imagenología Diagnóstica y Terapéutica'],
  ['rehabilitation', 'Medicina de Rehabilitación'],
  ['emergency_medicine', 'Medicina de Urgencias'],
  ['occupational_medicine', 'Medicina del Trabajo y Ambiental'],
  ['sports_medicine', 'Medicina Deportiva'],
  ['family_medicine', 'Medicina Familiar'],
  ['internal_medicine', 'Medicina Interna'],
  ['nuclear_medicine', 'Medicina Nuclear e Imagenología Molecular'],
  ['palliative_medicine', 'Medicina Paliativa'],
  ['preventive_medicine', 'Medicina Preventiva'],
  ['pulmonology', 'Neumología'],
  ['ophthalmology', 'Oftalmología'],
  ['otolaryngology', 'Otorrinolaringología y Cirugía de Cabeza y Cuello'],
  ['clinical_pathology', 'Patología Clínica'],
  ['pediatrics', 'Pediatría'],
  ['psychiatry', 'Psiquiatría'],
  ['radiation_oncology', 'Radio Oncología'],
  ['orthopedics', 'Traumatología y Ortopedia'],
  ['urology', 'Urología'],
  ['undecided', 'Todavía no lo decido'],
] as const satisfies readonly (readonly [string, string])[];
