-- Sincronización entre dispositivos (D-085 fila 12, D-095, Etapa 6 de la Fase C2).
--
-- Qué guarda
--   sync_records   los mazos, notas, tarjetas y apuntes propios del alumno y la distribución de su
--                  Inicio. Una fila por registro, con el registro completo en data (jsonb). El
--                  navegador lo valida con zod al bajarlo, así un cambio de esquema del cliente no
--                  pide una migración aquí
--   events         la bitácora que ya existía. Se le suma seq, un contador para bajar solo lo nuevo,
--                  y schema_version. Sigue siendo de solo agregar
--
-- Cómo se resuelve un conflicto
--   Gana la edición con updated_at más reciente. Un borrado es una fila con deleted_at, así que otro
--   dispositivo se entera. Si dos ediciones traen exactamente el mismo updated_at, se queda la que
--   ya estaba en el servidor, y los navegadores adoptan la del servidor al bajar. Con esa regla todos
--   convergen a lo mismo sin importar el orden en que sincronicen
--
-- Por qué las escrituras pasan por funciones y no por la tabla
--   El cliente no puede escribir en sync_records ni saltarse la regla de la fecha más reciente. Solo
--   sync_push_records escribe, y lo hace con los permisos de su dueño. Las dos funciones de subida
--   toman un candado por usuario durante la transacción, así el contador seq sale en el mismo orden
--   en que se confirman las subidas y quien baja con un cursor nunca se salta una fila
--
-- Quién puede usarlo
--   Solo el dispositivo activo de la cuenta (is_active_device, migración 20261008000001). Un
--   dispositivo desplazado conserva su token, pero ya no sube ni baja nada
--
-- Es idempotente. No edita las migraciones anteriores

-- ===================================================================== Registros
create sequence if not exists public.sync_records_seq as bigint;

create table if not exists public.sync_records (
  user_id uuid not null references auth.users (id) on delete cascade,
  kind text not null check (kind in ('deck', 'note', 'card', 'outline', 'widget_layout')),
  record_id text not null check (char_length(record_id) between 1 and 64),
  data jsonb not null check (jsonb_typeof(data) = 'object'),
  updated_at timestamptz not null,
  deleted_at timestamptz,
  server_seq bigint not null,
  primary key (user_id, kind, record_id)
);
create index if not exists sync_records_user_seq on public.sync_records (user_id, server_seq);

alter table public.sync_records enable row level security;
-- En Supabase las tablas nuevas nacen con permisos de escritura para la API. Aquí no se quiere
-- ninguno. Solo se lee, y la política limita a lo propio
revoke all on public.sync_records from public, anon, authenticated, service_role;
revoke all on sequence public.sync_records_seq from public, anon, authenticated, service_role;
grant select on public.sync_records to authenticated;

drop policy if exists sync_records_select on public.sync_records;
create policy sync_records_select on public.sync_records for select to authenticated
  using (user_id = auth.uid() and (select public.is_active_device()));

-- ===================================================================== Bitácora
-- El contador entra con un default de identidad. Postgres reescribe la tabla y llena las filas
-- que ya existían sin disparar el freno de edición de la bitácora
alter table public.events add column if not exists seq bigint generated by default as identity;
alter table public.events add column if not exists schema_version integer not null default 1;
create index if not exists events_user_seq on public.events (user_id, seq);

-- ===================================================================== Reloj
-- La hora del servidor. El navegador la compara con la suya antes de subir cambios, porque la regla
-- de la fecha más reciente solo vale si los relojes se parecen
create or replace function public.sync_clock() returns timestamptz
language sql stable set search_path = public, pg_temp as $$
  select clock_timestamp()
$$;

-- ===================================================================== Subir registros
-- Recibe un arreglo de hasta 500 registros {kind, id, updatedAt, deletedAt, data}. Devuelve cuántos
-- cambió de verdad. Un registro más viejo o igual al que ya hay no cambia nada
create or replace function public.sync_push_records(p_records jsonb) returns integer
language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_user uuid := auth.uid();
  v_rec jsonb;
  v_changed integer := 0;
  v_rows integer;
  v_updated timestamptz;
  v_deleted timestamptz;
begin
  if v_user is null then
    raise exception 'Hace falta iniciar sesión' using errcode = '28000';
  end if;
  if not public.is_active_device() then
    raise exception 'Este dispositivo no es el activo de la cuenta' using errcode = '42501';
  end if;
  if p_records is null or jsonb_typeof(p_records) <> 'array' then
    raise exception 'Se esperaba un arreglo de registros' using errcode = '22023';
  end if;
  if jsonb_array_length(p_records) > 500 then
    raise exception 'Máximo 500 registros por subida' using errcode = '22023';
  end if;

  perform pg_advisory_xact_lock(hashtextextended('sync:' || v_user::text, 0));

  for v_rec in select value from jsonb_array_elements(p_records) loop
    if jsonb_typeof(v_rec) <> 'object'
       or (v_rec ->> 'kind') is null
       or (v_rec ->> 'kind') not in ('deck', 'note', 'card', 'outline', 'widget_layout')
       or (v_rec ->> 'id') is null
       or char_length(v_rec ->> 'id') not between 1 and 64
       or jsonb_typeof(v_rec -> 'data') <> 'object'
       or octet_length((v_rec -> 'data')::text) > 262144 then
      raise exception 'Registro de sincronización inválido' using errcode = '22023';
    end if;
    v_updated := (v_rec ->> 'updatedAt')::timestamptz;
    v_deleted := nullif(v_rec ->> 'deletedAt', '')::timestamptz;
    if v_updated is null then
      raise exception 'Falta updatedAt' using errcode = '22023';
    end if;
    -- Una fecha en el futuro lejano ganaría todos los conflictos para siempre. Un navegador sano
    -- ya revisó su reloj contra sync_clock, así que esto solo frena a uno manipulado
    if v_updated > clock_timestamp() + interval '10 minutes' then
      raise exception 'updatedAt está en el futuro' using errcode = 'SY002';
    end if;

    insert into public.sync_records as r (user_id, kind, record_id, data, updated_at, deleted_at, server_seq)
    values (
      v_user, v_rec ->> 'kind', v_rec ->> 'id', v_rec -> 'data', v_updated, v_deleted,
      nextval('public.sync_records_seq')
    )
    on conflict (user_id, kind, record_id) do update
      set data = excluded.data,
          updated_at = excluded.updated_at,
          deleted_at = excluded.deleted_at,
          server_seq = excluded.server_seq
      where excluded.updated_at > r.updated_at;
    get diagnostics v_rows = row_count;
    v_changed := v_changed + v_rows;
  end loop;
  return v_changed;
end;
$$;

-- ===================================================================== Subir eventos
-- Solo agrega. Un evento que ya estaba (mismo id) se ignora, así subir dos veces no duplica. Devuelve
-- cuántos eventos nuevos quedaron guardados
create or replace function public.sync_push_events(p_events jsonb) returns integer
language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_user uuid := auth.uid();
  v_event jsonb;
  v_added integer := 0;
  v_rows integer;
  v_at timestamptz;
begin
  if v_user is null then
    raise exception 'Hace falta iniciar sesión' using errcode = '28000';
  end if;
  if not public.is_active_device() then
    raise exception 'Este dispositivo no es el activo de la cuenta' using errcode = '42501';
  end if;
  if p_events is null or jsonb_typeof(p_events) <> 'array' then
    raise exception 'Se esperaba un arreglo de eventos' using errcode = '22023';
  end if;
  if jsonb_array_length(p_events) > 500 then
    raise exception 'Máximo 500 eventos por subida' using errcode = '22023';
  end if;

  perform pg_advisory_xact_lock(hashtextextended('sync:' || v_user::text, 0));

  for v_event in select value from jsonb_array_elements(p_events) loop
    if jsonb_typeof(v_event) <> 'object'
       or (v_event ->> 'id') is null
       or char_length(v_event ->> 'id') not between 1 and 64
       or (v_event ->> 'type') is null
       or char_length(v_event ->> 'type') not between 1 and 64
       or (v_event ->> 'tz') is null
       or char_length(v_event ->> 'tz') not between 1 and 64
       or jsonb_typeof(v_event -> 'payload') <> 'object'
       or octet_length((v_event -> 'payload')::text) > 65536 then
      raise exception 'Evento de sincronización inválido' using errcode = '22023';
    end if;
    v_at := (v_event ->> 'at')::timestamptz;
    if v_at is null then
      raise exception 'Falta at' using errcode = '22023';
    end if;
    if v_at > clock_timestamp() + interval '10 minutes' then
      raise exception 'at está en el futuro' using errcode = 'SY002';
    end if;

    insert into public.events (id, user_id, type, at, tz, session_id, payload, schema_version)
    values (
      v_event ->> 'id', v_user, v_event ->> 'type', v_at, v_event ->> 'tz',
      nullif(v_event ->> 'sessionId', ''), v_event -> 'payload',
      coalesce((v_event ->> 'schemaVersion')::integer, 1)
    )
    on conflict (id) do nothing;
    get diagnostics v_rows = row_count;
    v_added := v_added + v_rows;
  end loop;
  return v_added;
end;
$$;

-- ===================================================================== Permisos
revoke all on function public.sync_clock() from public, anon, service_role;
grant execute on function public.sync_clock() to authenticated;
revoke all on function public.sync_push_records(jsonb) from public, anon, service_role;
grant execute on function public.sync_push_records(jsonb) to authenticated;
revoke all on function public.sync_push_events(jsonb) from public, anon, service_role;
grant execute on function public.sync_push_events(jsonb) to authenticated;
